# Generated by Django 4.1.6 on 2023-05-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_rename_tweets_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-id']},
        ),
    ]
